platform :ios, '17.4'

target 'iosApp' do
  use_frameworks!

  pod 'lib', :path => '../lib'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.4'
    end
  end
end