# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'lottie-ios', '~> 4.0'
end